"""
This type stub file was generated by cyright.
"""
import sys

if sys.version_info <= (3, 11):
    from typing_extensions import Buffer
else:
    from collections.abc import Buffer

class sha1:
    """uses the sha1 hashing algorythm."""
    def __init__(self, data: Buffer = b"", useforsecurity: bool = False) -> None:
        """Return a new SHA1 hash object."""
        ...
    
    @property
    def digest_size(self) -> int:
        ...
    
    @property
    def block_size(self) -> int:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    def copy(self) -> sha1:
        """Return a copy of the hash object."""
        ...
    
    def hexdigest(self) -> str:
        ...
    
    def digest(self) -> bytes:
        ...
    
    def update(self, obj: object) -> object:
        """Update this has object's state with the provided string."""
        ...

_GIL_MINSIZE: int
